server:
  port: 5000

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: mappings
    jmx:
      exposure:
        include: health,info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soccer_api?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
    username: root
    password: pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl